### PR TITLE
Add phpDoc for methods and properties

### PR DESCRIPTION
**Pull request by erikgaal**
This PR adds phpDoc for all methods and properties of the latest puppeteer. Very useful for anyone using an IDE as this brings code completion and inspection for otherwise "magic" code.

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
100% love this idea :)

https://github.com/nesk/puphpeteer/issues/27

**Comment by nesk** [comment]
First of all, thank you for your PR! This must have took quite some time…

Unfortunately, just like I said in #27, I'm not sure I want those hand-written definitions in PuPHPeteer, because I will have to maintain all of them and I _know_ I will _not_, we will definitely have outdated definitions.

However, I can perfectly understand this is something you want, or even need. So I've been thinking about a solution and its probably possible to _generate_ the documentation. JSDoc has [a command-line which can output a JSON structure (with the `-X` option)](http://usejsdoc.org/about-commandline.html) describing all the code in JS files, I think we can extract what we need from this and then automatically write the PHP docs.

I'm currently a bit in a rush so I can't work on it right now, but I will try to work on this as soon as possible. I'm also open to suggestions. 🙂

I'm keeping your PR open until I create an appropriate issue.

**Comment by erikgaal** [comment]
Hi @nesk, thanks for your response!

Automatically generating the definitions from the actual JS code seems like a nice solution. Because implementing something that will automatically paste in the phpDocs in the code could be tricky and destructive (I think?), I just thought of a solution that involves adding a test case that checks if the two docs are equal. This should work fine because you're still manually updating the puppeteer version anyways.

To implement such a test we could parse the phpDocs using [ReflectionClass::getDocComment()](http://php.net/manual/en/reflectionclass.getdoccomment.php) and compare the two. We would have to find a way to compare cases such as:

`Promise` and `void`
`Promise<?Response>` and `Response|null`

**Comment by nesk** [comment]
A simple `git diff` review will be enough to avoid destructive overrides.

My concern is more about #23, because the latest Puppeteer version could be used with an earlier version of Puphpeteer and it could have outdated definitions.

**Comment by erikgaal** [comment]
Then I propose to lock the puppeteer version down to minor in `package.json`, without the use of `~` or `^`.

**Comment by erikgaal** [comment]
Tracking work in #38 on generating phpDocs from Puppeteer's JavaScript source.

**Comment by nesk** [comment]
I'm closing since you opened a new PR for this.

**Pull request closed without merging**
