### PR TITLE
update dependancy to symfony 5

### PR DESCRIPTION
**Pull request by psohm**

### CODE REVIEW

**Comment by irazasyed** [comment]
Can we have this merged, please?

**Comment by irazasyed** [comment]
@nesk Can you please merge this?

**Comment by raykudo** [comment]
@nesk please merge this PR

**Comment by Vincz** [comment]
@nesk hey :) Could you merge this PR plz ?

**Comment by husonghua** [comment]
@nesk, could you please merge this PR please?

**Comment by spekulatius** [comment]
Context: PR was duplicated - https://github.com/nesk/puphpeteer/blob/dev/composer.json

**Pull request closed without merging**
