### PR TITLE
Generate phpDoc from JSDoc command

### PR DESCRIPTION
**Pull request by erikgaal**
*This is a work in progress.*

This PR adds a command to generate `@method` and `@property` phpDoc from the actual puppeteer JS source.

### CODE REVIEW

**Comment by erikgaal** [comment]
This is ready for a review now, @nesk.

**Comment by nesk** [comment]
Amazing! I will review this asap but I will be quite busy for one more week (I'm working on another project with a deadline), sorry for making you wait.

Until I give you a full review, here are a few observations:

- I don't think the class name in php docs is required above each resource class.
- Why are you requiring `ext-json` in Composer?
- We should really have some tests for this.

One point I really can't allow is the helpers file. You're creating global functions, what if someone needs to create a function named `str_startswith` but we already created it before him? This is a library, not a framework. We could go with a `Helper` class with static functions, but honestly some of them are pretty useless:

- `str_contains($haystack, $needles)` could be replaced with `strstr($haystack, $needle) !== false`, you're not using the array as a second parameter.
- `array_get($array, $key, $default)` could be replaced with `$array[$key] ?? $default`, we're targeting PHP 7.1+ so we have the null coalescing operator `??`.
- And it goes on… I think all the functions can be removed. I know its not as readable, but I would like to avoid declaring them for only one use.

The `thightenco/collect` package is great, I love it too, but it creates some global functions too, I would really like to avoid this and I see you're not making a heavy usage of it, so we can probably get rid of it.

And finally, about your commits:

- You shouldn't include the generated php docs in this PR, they are the result of it, not a part of the generative code.
- The day I will merge this, I will probably rework your commits in fewer ones (I try to keep them tidy), you will keep the authoring of course but you will have less commits in your stats, I hope you're okay with this?

Congrats on the PR, and a huge thank you!

**Comment by erikgaal** [comment]
Hi @nesk, thanks for the first part of your review.

> I don't think the class name in php docs is required above each resource class.

It's not so I will remove them to clean it up.

> Why are you requiring `ext-json` in Composer?

Using `json_*` in your code makes PhpStorm suggest the inclusion in `composer.json`, it can't see the difference between _production_ and _dev_ code.

> We should really have some tests for this.

I will be extracting some of the formatting code to a support class so we can test more. I'm not sure if we can test the actual running of the commands, but we should make sure to test the components themself.

> And it goes on… I think all the functions can be removed. I know its not as readable, but I would like to avoid declaring them for only one use.

I'd prefer to keep them in a `Str` or `Helper` class, but if you think I should avoid that at all, I'll comply.

> You shouldn't include the generated php docs in this PR, they are the result of it, not a part of the generative code.

Reverted that.

> The day I will merge this, I will probably rework your commits in fewer ones (I try to keep them tidy), you will keep the authoring of course but you will have less commits in your stats, I hope you're okay with this?

That's fine.

**Comment by nesk** [comment]
> Using `json_*` in your code makes PhpStorm suggest the inclusion in `composer.json`, it can't see the difference between _production_ and _dev_ code.

[The JSON extension is part of PHP since v5.2](http://php.net/manual/en/json.installation.php) and we're targeting PHP 7.1+, so you can remove this.

> > We should really have some tests for this.
> 
> I will be extracting some of the formatting code to a support class so we can test more. I'm not sure if we can test the actual running of the commands, but we should make sure to test the components themself.

Yes, just start with unit testing, we will see later for functional ones.

> > And it goes on… I think all the functions can be removed. I know its not as readable, but I would like to avoid declaring them for only one use.
> 
> I'd prefer to keep them in a `Str` or `Helper` class, but if you think I should avoid that at all, I'll comply.

I understand you're used to these functions, but they're not used anywhere else in PuPHPeteer's code. If you _really_ need a helper, you could add it as a protected method in your command class.

**Comment by erikgaal** [comment]
> [The JSON extension is part of PHP since v5.2](http://php.net/manual/en/json.installation.php) and we're targeting PHP 7.1+, so you can remove this.

TIL, changed that, wonder why PhpStorm is still complaining then.

> Yes, just start with unit testing, we will see later for functional ones.

Added some unit tests for the formatting methods. Any suggestions what other parts I could test?

> I understand you're used to these functions, but they're not used anywhere else in PuPHPeteer's code. If you _really_ need a helper, you could add it as a protected method in your command class.

Removed all global helpers and added just the `group` and `sort` protected methods to keep the code readable.

**Comment by erikgaal** [comment]
When would you be available to take a look at this again, @nesk?

**Comment by nesk** [comment]
Sorry for the delay, I had more work than expected, I started a review of your code but had no time to finish it… However, I promise I will work on this at the end of this week. 🙂

**Comment by jonnywilliamson** [comment]
@erikgaal very excited to see this in action. Nice job! Thank you.

**Comment by nesk** [comment]
So, I finally had some time to work on your PR!

First, let's talk about the command itself:

- Put the command in a `Command` directory instead of `Console`
- Use PHP's type hinting instead of PHPdoc comments, you can leave `@var` tags for properties but remove `@param` and `@return` for methods if there's an equivalent in PHP
- Use Symfony's Process instead of `shell_exec()`, I already use this class in my code
- Instanciate JSDocFormatter instead of defining a static property
- About the `Cannot find Resource class [...]` warning, we shouldn't work that way. We should instead list all the resources we have in PuPHPeteer, then check for their counterparts in Puppeteer, and if something's missing (a PHP resource doesn't have a JS counterpart) then we output a warning.

About the generated documentation:

- Undocumented methods are ignored, like these ones:
  - `Browser::disconnect()`
  - `BrowserContext::close()`
  - `CDPSession::detach()`
  - etc…
- Nullable types aren't handled, examples:
  - second parameter of `BrowserFetcher::download()`
  - return value of `ElementHandle::boundingBox()`
  - etc…
- Static methods shouldn't be documented, we don't handle them (and Puppeteer doesn't document any of them on [pptr.dev](https://pptr.dev)), for example: `Browser::create()`
- Non-serializable JS types (typically, class instances) without any PHP counterparts should be documented as `\Nesk\Rialto\Data\BasicResource` instead of `array`. To find them, just look if the type is declared in JSDoc as `"kind": "typedef"`, if it's not then you can document with `BasicResource`. Here are examples:
  - return value of `Browser::process()`
  - return value of `ElementHandle::screenshot()`
  - etc…
- Don't document the `toString()` method on any resource (`JSHandle` for example), I will support string casting in Rialto: nesk/rialto#17

Here are things currently missing I will take care of:

- Add typings to the traits methods: nesk/puphpeteer#43
- Apply class inheritance, for example `ElementHandle` should inherit from `JSHandle`: nesk/puphpeteer#42

Honestly, if you think you've done enough, I can finish the work for the PR if you want, just let me know. 😉

**Comment by erikgaal** [comment]
Hi @nesk, many thanks for doing the review. I will look into most of the points you've provided me with and get back to you shortly. 😁

**Comment by jonnywilliamson** [comment]
@erikgaal is on fire 🔥 👍

**Comment by nesk** [comment]
Everything seems good, I will merge this asap. Thank you for your work! 💪

The release including this PR might take a bit of time because I would like to release this in the v2 with other features.

**Comment by erikgaal** [comment]
@nesk It was my pleasure!

> About the Cannot find Resource class [...] warning, we shouldn't work that way. We should instead list all the resources we have in PuPHPeteer, then check for their counterparts in Puppeteer, and if something's missing (a PHP resource doesn't have a JS counterpart) then we output a warning.

I did not attempt to fix this yet, and I'm currently running slightly out of time, maybe you can take a look at this?

**Comment by nesk** [comment]
Yeah, don't worry, I will finish what's eventually missing. 😉

**Comment by nesk** [comment]
Manually merged in dev. Thank you for your work @erikgaal!

**Pull request closed without merging**
